import React from 'react'
import Terms from './Terms'

 const Privacy = () => {
  return (
   <>
     <Terms title={'Privacy Policy'} welcome={` Welcome to Movie Spot's Privacy Policy. We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our policy or practices with regards to your personal information, please contact us at moviesspot@gmail.com.`} policy1={`1. Information We Collect`} policy1info={'   We collect personal information that you voluntarily provide to us when registering at Movie Spot, expressing an interest in obtaining information about us or our products and services, when participating in activities on the website, or otherwise contacting us.'} policy2 = {`2. How We Use Your Information`} policy2info={` We use personal information collected via our website for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations.`} policy3={`3. Sharing Your Information`} policy3info={' We only share and disclose your information in the following situations: compliance with laws, vital interests and legal rights, vendors, consultants, and other third-party service providers, business transfers, and with your consent.'} policy4={`4. Cookies and Tracking Technologies` } policy4info={` We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.`} policy5={'5. Data Security'} policy5info={` We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure.`} policy6={`6. Your Privacy Rights`} policy6info={` In some regions, such as the European Economic Area, you have rights that allow you greater access to and control over your personal information. You may review, change, or terminate your account at any time.`}policy7={`7. Updates to This Policy`} policy7info={` We may update this privacy policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons.`} policy8={'8. Contact Information'} policy8info={`  If you have questions or comments about this policy, you may contact us by email at moviesspot@gmail.com.`}   endcontext={' By using Movie Spot, you acknowledge that you have read this privacy policy and agree to its terms.'} />
   </>
  )
}

export default Privacy