export const showflixapi =[
            {
            "objectId": "bgMbcB8TXj",
            "movieName": "Kanguva (2024)",
            "rating": " 4",
            "storyline": "A story that travels 954 years from the 1070's to 2024 about a Hero who has to fulfil a mission left unfinished.",
            "poster": "https://www.themoviedb.org/t/p/original/lycbTFBXqFN1kMdPEsnAFutKEEy.jpg",
            "backdrop": "https://www.themoviedb.org/t/p/original/kW88HxGOB1nAZAK9k66vJtJC9GW.jpg",
            "category": "Tamil Telugu Malayalam Kannada",
            "streamlink": "https://embedsb.com/play/.html",
            "language": "ta",
            "hdlink": "https://showflix.shop/archives/8147",
            "sharedisk": "",
            "streamhide": "",
            "streamwish": "bhnxx3qp98ka",
            "filelions": "hzchg2amkdkl",
            "streamruby": "1bob6uit6ebb",
            "uploadever": "",
            "HubCloud": "https://showflix.shop/archives/8149",
            "upnShare": "nyps8",
            "tmdbid": "622792",
            "createdAt": "2024-12-08T03:02:51.002Z",
            "updatedAt": "2024-12-08T03:02:51.002Z"
        },
        {
            "objectId": "IHzbW4LC4x",
            "movieName": "Amaran (2024)",
            "rating": " 7.3",
            "storyline": "A heroic true story of Major Mukund Varadarajan, an Indian Army officer who displayed extraordinary bravery during a counterterrorism mission in Kashmir’s Shopian district. The film captures his courage in protecting his nation and the devotion of his wife Indhu Rebecaa Varghese.",
            "poster": "https://www.themoviedb.org/t/p/original/eCB06m1KUGilEOlIzb40nkQhVY0.jpg",
            "backdrop": "https://www.themoviedb.org/t/p/original/4sUUxs63Q5lGC1B2wN9Uc3NId2x.jpg",
            "category": "Tamil Telugu Hindi Malayalam Kannada",
            "streamlink": "https://embedsb.com/play/.html",
            "language": "ta",
            "hdlink": "https://showflix.shop/archives/8116",
            "sharedisk": "",
            "streamhide": "",
            "streamwish": "yivyvdznt5cg",
            "filelions": "o61wswcclmro",
            "streamruby": "d6qk7du1z747",
            "uploadever": "",
            "HubCloud": "https://showflix.shop/archives/8118",
            "upnShare": "9vybh",
            "tmdbid": "927342",
            "createdAt": "2024-12-07T04:21:11.766Z",
            "updatedAt": "2024-12-07T06:05:22.982Z"
        },
        {
            "objectId": "lTSvug3BbH",
            "movieName": "Lucky Baskhar (2024)",
            "rating": " 7.3",
            "storyline": "A cash-strapped bank cashier embarks on a risky investment scheme and soon gets drawn into the murky world of money laundering.",
            "poster": "https://www.themoviedb.org/t/p/original/jifHxS5kMd6pKGIh1R3oyFSyAKN.jpg",
            "backdrop": "https://www.themoviedb.org/t/p/original/gMmJQyLW1qTkixs9jL9RpcJ37Sx.jpg",
            "category": "Tamil Telugu Hindi Malayalam Kannada",
            "streamlink": "https://embedsb.com/play/.html",
            "language": "te",
            "hdlink": "https://showflix.shop/archives/8053",
            "sharedisk": "",
            "streamhide": "",
            "streamwish": "91d8z7l9yatp",
            "filelions": "sjbkj53ex0lp",
            "streamruby": "bcqtiap86e56",
            "uploadever": "",
            "HubCloud": "https://showflix.shop/archives/8055",
            "upnShare": "mdi6s",
            "tmdbid": "1239511",
            "createdAt": "2024-11-28T03:31:09.090Z",
            "updatedAt": "2024-11-28T03:31:09.090Z"
        }
    ]